# Generated by Django 3.2.10 on 2022-01-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomenclators', '0008_auto_20220107_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType', to='Nomenclators.producttype')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
