# Generated by Django 3.2.10 on 2022-01-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carrito Compra'},
        ),
    ]
