# Generated by Django 3.2.10 on 2022-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0004_auto_20220102_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateways',
            name='location_name',
        ),
        migrations.AddField(
            model_name='coin',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gateways',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gateways',
            name='cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gateways',
            name='charge',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='gateways',
            name='description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='gateways',
            name='ecommerce_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gateways',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gateways',
            name='gateway_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='gateways',
            name='secret_key',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='gateways',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='gateways',
            name='url_response',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='gateways',
            name='user_code',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
