# Generated by Django 3.2.10 on 2022-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0005_auto_20220102_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(default='', max_length=70)),
                ('secret_key', models.CharField(default='', max_length=1024)),
                ('user_code', models.CharField(default='', max_length=1024)),
                ('first', models.BooleanField(default=False)),
                ('cards', models.BooleanField(default=True)),
                ('ecommerce_code', models.CharField(default='', max_length=50)),
                ('charge', models.FloatField(default=1)),
                ('url', models.CharField(default='', max_length=256)),
                ('url_response', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=2048)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
            ],
        ),
        migrations.DeleteModel(
            name='Gateways',
        ),
    ]
