# Generated by Django 3.2.10 on 2022-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0007_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name': 'Pasarela', 'verbose_name_plural': 'Pasarelas'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localizacion', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='gateway_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='coin_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
