# Generated by Django 3.2.10 on 2022-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=4),
        ),
    ]
