# Generated by Django 3.2.10 on 2022-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0002_alter_country_iso3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(max_length=4),
        ),
    ]
