# Generated by Django 3.2.10 on 2022-01-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0003_auto_20220102_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=70)),
                ('base', models.BooleanField(default=False)),
                ('first', models.BooleanField(default=False)),
                ('value_change', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
            ],
        ),
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='action time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='change time')),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='action time'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='action time'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change time'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='Nomenclators.coin'),
        ),
    ]
