# Generated by Django 3.2.10 on 2022-01-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclators', '0006_auto_20220102_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
